image: nikolaik/python-nodejs

options:
  max-time: 10

pipelines:
  pull-requests:
    '**':
      - step:
          name: build check
          caches:
            - node
          script:
            - export REACT_APP_PRODUCTION_PROD=true
            - yarn install
            - yarn build
  branches:
    master:
      - step:
          name: deploy to Development
          deployment: development
          caches:
            - node
          script:
            - pip install awscli --upgrade --ignore-installed six
            - export REACT_APP_PRODUCTION_PROD=true
            - export VUE_APP_ASSETS_PATH="https://azalea.scan.onfinality.me"
            - yarn install
            - yarn build
            - aws s3 sync ./web s3://azalea.scan.onfinality.me
            - aws s3 cp --cache-control max-age=0 ./web/customizeConfig.js s3://azalea.scan.onfinality.me/customizeConfig.js
            - aws s3 cp --cache-control max-age=0 ./web/index.html s3://azalea.scan.onfinality.me/


      - step:
          name: deploy to Production
          deployment: production
          caches:
            - node
          trigger: manual
          script:
            - pip install awscli --upgrade --ignore-installed six
            - export REACT_APP_PRODUCTION_PROD=true
            - yarn install
            - yarn build
            - aws s3 sync ./web s3://azalea.scan.onfinality.io --exclude *.map
            - aws s3 cp --cache-control max-age=0 ./web/customizeConfig.js s3://azalea.scan.onfinality.io/customizeConfig.js
            - aws s3 cp --cache-control max-age=0 ./web/index.html s3://azalea.scan.onfinality.io/

