apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.appName}}-service
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.appName}}-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{.Values.appName}}-service
  minReplicas: {{.Values.autoscaling.minReplicas | default "2"}}
  maxReplicas: {{.Values.autoscaling.maxReplicas | default "10"}}
  targetCPUUtilizationPercentage: {{.Values.autoscaling.targetCPUUtilizationPercentage | default "50"}}
