{{- if eq .Values.requiresInternalEndpoint true }}
apiVersion: v1
kind: Service
metadata:
  name: invalid-service
  namespace: {{.Values.namespace}}
  labels:
    app: invalid-service
spec:
  type: ExternalName
  externalName: default-http-backend.ingress-nginx.svc.cluster.local
---
{{- end }}
{{- if .Values.externalServices }}
{{- $root := . -}}
{{- range $i, $es := .Values.externalServices}}
apiVersion: v1
kind: Service
metadata:
  name: {{$es.name}}
  namespace: {{$root.Values.namespace}}
  labels:
    app: {{$es.name}}
spec:
  type: ExternalName
  externalName: {{$es.name}}.{{$es.namespace}}.svc.cluster.local
---
{{- end }}
{{- end }}
