apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}-service
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.appName}}-service
spec:
  ports:
  - port: {{.Values.service.port | default 8080}}
  selector:
    app: {{.Values.appName}}-service
